### ISSUE TITLE
Alpine Linux support or some help please?

### ISSUE THREAD

**Issue by gspannu** [m0zgen/blocky-installer#5]
Hi,

I would like to use Blocky DNS on Alpine Linux.

_Blocky is available on the Alpine edge/testing channel._

Could you modify your installation scripts to include Apline Linux?

Or, could you just send some instructions to create the basic service start/stop/restart/status files for Alpine Linux - and I will manually install and create the necessary files? 
I am a bit of a newbie to Alpine.... so do not know the service daemon bits (I know how to do this in Debian, but not Alpine).

_I am just looking to test Blocky in Alpine at the moment, so even installing as root user for the moment is fine._ Just need to be able to install Blocky as a service and auto-start at boot.

**Could you provide some assistance?** Thanks.

**Comment by m0zgen** [comment]
hi, thanks for your interest. this is out the scope of the project, but you can experiment with assemblies, as for example described in this article, there is also a ready-made package in the alpine repository, which you can also use according to your requirements, see links below:
- https://megamorf.gitlab.io/2019/09/08/alpine-go-builds-with-cgo-enabled/
- https://pkgs.alpinelinux.org/package/edge/testing/x86/blocky
- Write init scripts - https://wiki.alpinelinux.org/wiki/Writing_Init_Scripts
- Blocky example script in alpine issue - https://gitlab.alpinelinux.org/alpine/aports/-/issues/14968

**Comment by gspannu** [comment]
I eventually managed to get it working on Alpine Linux !

_Below is a short guide for reference (it may help someone else)..._

---

#) Search for Blocky from edge/testing repository
`apk --no-cache search blocky --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing`

#) Install Blocky from edge/testing repository
`apk --no-cache add blocky --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing`

#) Check that blocky has been installed. e.g. in /usr/bin
`ls -lAhp /usr/bin | grep blocky`

#) Create the service file for Blocky
`nano /etc/init.d/blocky`

```
#!/sbin/openrc-run
name="${RC_SVCNAME}"
description="Blocky is a DNS server with ad-blocker"
command="/usr/bin/blocky"
pidfile="/run/${RC_SVCNAME}.pid"
required_files="/etc/blocky/config.yml"
command_args="-c /etc/blocky/config.yml"
command_background=yes
command_user="root:root"
output_log="/var/log/blocky/${RC_SVCNAME}.log"
error_log="/var/log/blocky/${RC_SVCNAME}.err"
```

#) Make the above Blocky init script executable
`chmod a+x /etc/init.d/blocky`

#) Create your config.yml file

`mkdir -p /etc/blocky`
`nano  /etc/blocky/config.yml`

#) Start blocky manually to test if it works
`blocky -c /etc/blocky/config.yml`

#) Press Ctrl-C to exit out

#) Start Blocky service and check
`rc-service blocky start`
`rc-service blocky status`

#) Check that service is running
`nano /var/log/blocky/blocky.log`

#) Check that Blocky is rinning on port 53 (or whatever port your config.yml states)
`netstat -tunlp`

#) Enable Blocky to start at boot-up
`rc-update add blocky`

#) Check Blocky as a service
`rc-service --list | grep blocky`
`rc-update`

#) Reboot machine and check that Blocky is running as expected !

---

**Comment by m0zgen** [comment]
Good references. Thanks!
