### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by ThinkChaos** [m0zgen/blocky-installer#6]
Hi,

I'm updating the installation docs for blocky and am wondering if we should keep this in?  
Right now the section linking this is called "Installation script for CentOS/Fedora" should that be updated?  
I know there's been a lot of drama with Red Hat/Centos so just checking in :)

**Comment by m0zgen** [comment]
Hi, 

Thank you for information about of update documentation activities. 

Yes - at current time installer working on CentOS, Fedora, Debian. 

Early, there were problems with repositories and releases, but on current time there are several other os like as Alma, Rocky but it’s still the same CentOS RPM-based  distro...)

As far as I know people sometimes use this installer, I think leaving a link might be useful for some blocky users.

**Comment by ThinkChaos** [comment]
Ok thanks for the reply!  
I'll add Debian to the mentionned distros.
